#!/bin/bash

hda=""
hdb=""

while [ "$1" != "" ]
do
  case "$1" in
    "-hda")
      shift
      hda=$1
      ;;
    "-hdb")
      shift
      hdb=$1
      ;;
    "-help" | "-h" | "--help")
      echo "./run -hda <minix.img> -hdb <second drive>"
      exit
      ;;
    *)
      echo "Type ./run -help"
      exit
      ;;
  esac
  shift
done
if [ "$hda" == "hgay1" ]
then
  hda="/vm/cs-301b/hgay1/minix.img"
fi
ta=$([ -f "$hda" ] && echo "Found" || echo "Not Found")
tb=$([ -f "$hdb" ] && echo "Found" || echo "Not Found")
if [ "$ta" == "Not Found" ] || [ "$tb" == "Not Found" ]
then
  echo "One of the files dose not exist"
  echo "hda: $ta"
  echo "hdb: $tb"
  exit
fi
qemu-system-i386 -m 64M -net nic,model=ne2k_pci -net user,hostfwd=tcp::2021-10.0.2.15:21 -hda "$hda" -hdb "$hdb" 

